### ISSUE TITLE
Import of a checklist from JSON crushes the app

### ISSUE THREAD

**Issue by octennially** [SimpleMobileTools/Simple-Notes#349]
Import of a checklist from a JSON file currently doesn't work. The app crushes after the file selection from the file-picker dialog, before the "Add a new note" dialog (with the name and note type) is shown.

#### Environment
OS: Android 10 (LineageOS)
App version: 6.5.1 or current master HEAD (cc3bbef)
Permissions granted: Read storage (so that in-app file pick dialog is used)

#### Description
Prerequisites:
 - checklist note exported as a JSON file, preferably from the same app version

Steps reproduce:
 1. app menu
 1. "Open file"
 1. "Select a file" dialog is shown
 1. select the JSON file with a checklist
 1. the app immediately crushes, the note is not imported
 1. after the reopening of the app, the imported checklist is also not present

Expected: after the 4. step appears "Add a new note" dialog, to complete the import.

#### Crash stacktrace
        --------- beginning of crash
    E/AndroidRuntime: FATAL EXCEPTION: Thread-20
        Process: com.simplemobiletools.notes.pro.debug, PID: 10031
        java.lang.RuntimeException: Can't create handler inside thread Thread[Thread-20,5,main] that has not called Looper.prepare()
            at android.os.Handler.<init>(Handler.java:207)
            at android.os.Handler.<init>(Handler.java:119)
            at android.app.Dialog.<init>(Dialog.java:133)
            at android.app.Dialog.<init>(Dialog.java:181)
            at androidx.appcompat.app.AppCompatDialog.<init>(AppCompatDialog.java:57)
            at androidx.appcompat.app.AlertDialog.<init>(AlertDialog.java:98)
            at androidx.appcompat.app.AlertDialog$Builder.create(AlertDialog.java:983)
            at com.simplemobiletools.notes.pro.dialogs.NewNoteDialog.<init>(NewNoteDialog.kt:29)
            at com.simplemobiletools.notes.pro.activities.MainActivity.displayNewNoteDialog(MainActivity.kt:488)
            at com.simplemobiletools.notes.pro.activities.MainActivity.access$displayNewNoteDialog(MainActivity.kt:44)
            at com.simplemobiletools.notes.pro.activities.MainActivity$openFile$1$1$1.invoke(MainActivity.kt:541)
            at com.simplemobiletools.notes.pro.activities.MainActivity$openFile$1$1$1.invoke(MainActivity.kt:44)
            at com.simplemobiletools.commons.helpers.ConstantsKt$ensureBackgroundThread$1.run(Constants.kt:308)
            at java.lang.Thread.run(Thread.java:919)

#### Suspected cause
The "Add a new note" dialog is invoked from non-UI thread.

#### Possible fix
 - Ensure the NewNoteDialog is intantiated in a UI tread by wrapping the AlertDialog.Builder call with Activity.runOnUiThread.
 - Or add the Activity.runOnUiThread into the Activity.setupDialogStuff in the commons. Call from within a UI thread is a problem (https://developer.android.com/reference/android/app/Activity#runOnUiThread(java.lang.Runnable)), so it should be safe.

**Comment by tibbi** [comment]
should be fixed already
