### ISSUE TITLE
Selecting text and clicking anywhere leads to crash

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/Simple-Notes#93]
Make links active option must be enabled to make this reproduce.

**Comment by trubitsyn** [comment]
`Process: com.simplemobiletools.notes, PID: 14749
                                                                             java.lang.IllegalArgumentException: Invalid offset: -1. Valid range is [0, 5]
                                                                                 at android.text.method.WordIterator.checkOffsetIsValid(WordIterator.java:380)
                                                                                 at android.text.method.WordIterator.isBoundary(WordIterator.java:101)
                                                                                 at android.widget.Editor$SelectionStartHandleView.positionAtCursorOffset(Editor.java:4285)
                                                                                 at android.widget.Editor$HandleView.updatePosition(Editor.java:3733)
                                                                                 at android.widget.Editor$PositionListener.onPreDraw(Editor.java:2510)
                                                                                 at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2475)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1354)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6902)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:895)
                                                                                 at android.os.Handler.handleCallback(Handler.java:815)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                 at android.os.Looper.loop(Looper.java:227)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6100)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:859)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
                                                                                 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)`

**Comment by tibbi** [comment]
how to reproduce it? Im not sure whats the issue

**Comment by trubitsyn** [comment]
Type any text. Select. Click on theselected text or anywhere in the EditText.

**Comment by trubitsyn** [comment]
Important: after enabling qctive links you need to close and reopen the app to make new settings apply.

**Comment by trubitsyn** [comment]
Complete guide:
1. Make links active
2. Destroy the app
3. Open the app
4. Type text
5. Select it so it is highlighted
6. Click on it

I'm sorry I didn't provide steps to reproduce earlier.

**Comment by trubitsyn** [comment]
@tibbi please look at #94 when you have time to.
